spring:
  application:
    name: siteFrontend

  data.mongodb:
    database: site


  resources:
    chain:
    #TODO md5 versioning ?
      strategy.content:
        enabled: true
        paths: /*,/static/**

server:
  port: 80
  contextPath: /site

logging.level.root: WARN

app.siteFrontend:
  appConfig:
    adminUserName: tkl
    adminPassword: 123
